name: Build Containers

on:
  push:
    branches:
      - initial
    # tags:
    #   - 'v*'

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Build containers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Get docker info"
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: "Log into GitHub Container Registry"
        if: "github.event_name != 'pull_request'"
        uses: "docker/login-action@v1"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Get Cassandra versions
        run: |
          cass5=$(curl -sL https://raw.githubusercontent.com/docker-library/cassandra/refs/heads/master/5.0/Dockerfile | grep "ENV CASSANDRA_VERSION" | awk '{print $3}')
          echo "CASS5_VERSION=${cass5}" >> $GITHUB_ENV
          cass4=$(curl -sL https://raw.githubusercontent.com/docker-library/cassandra/refs/heads/master/4.0/Dockerfile | grep "ENV CASSANDRA_VERSION" | awk '{print $3}')
          echo "CASS4_VERSION=${cass4}" >> $GITHUB_ENV
          cass41=$(curl -sL https://raw.githubusercontent.com/docker-library/cassandra/refs/heads/master/4.1/Dockerfile | grep "ENV CASSANDRA_VERSION" | awk '{print $3}')
          echo "CASS41_VERSION=${cass41}" >> $GITHUB_ENV

      - name: Build the official cassandra base image 5.0
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.CASS5_VERSION }}
            GitCommit=${{ github.sha }}
          context: cassandra/5.0
          push: true
          file: cassandra/5.0/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/cassandra:${{ env.CASS5_VERSION }}
          labels: |
            LABEL org.opencontainers.image.source="https://github.com/${{ env.REPO_OWNER }}/axonops-workbench-containers"

      - name: Prepare 5.0 AxonOps Workbench Dockerfile
        run: |
          cp Dockerfile-template Dockerfile

          sed -i "s|%BASE_IMAGE%|ghcr.io/${{ env.REPO_OWNER }}/cassandra:${{ env.CASS5_VERSION }}|g" Dockerfile
          MAJOR_VERSION="${VERSION%.*}"
          sed -i "s/{{MAJOR_VERSION}}/$VER/g" Dockerfile
      
      - name: Build the AxonOps Workbench image 5.0
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ env.CASS5_VERSION }}
            GitCommit=${{ github.sha }}
          context: .
          push: true
          file: cassandra/5.0/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/wb-cassandra:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/wb-cassandra:${{ env.TAG }}
          labels: |
            LABEL org.opencontainers.image.source="https://github.com/${{ env.REPO_OWNER }}/axonops-workbench-containers"
