---
name: Validate Image Manifests
on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      fix_missing:
        description: 'Automatically remove missing images from manifest.json'
        required: false
        type: boolean
        default: false

jobs:
  validate:
    name: Validate Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up crane
        uses: imjasonh/setup-crane@v0.3

      - name: Authenticate to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | crane auth login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Validate images
        id: validate
        run: |
          set +e  # Don't exit on error
          
          if [ "${{ github.event.inputs.fix_missing }}" = "true" ]; then
            ./scripts/validate-images.sh --fix
            exit_code=$?
          else
            ./scripts/validate-images.sh
            exit_code=$?
          fi
          
          # Capture validation output for issue creation
          ./scripts/validate-images.sh 2>&1 | tee validation_output.txt || true
          
          # Set output for next steps
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          
          # Extract missing images count
          missing_count=$(grep -c "MISSING" validation_output.txt || echo "0")
          echo "missing_count=$missing_count" >> $GITHUB_OUTPUT
          
          exit $exit_code

      - name: Create issue for missing images
        if: failure() && github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('validation_output.txt', 'utf8');
            
            // Extract missing images information
            const missingSection = output.split('Missing images detected!')[1] || '';
            const missingImages = missingSection.match(/Version: (.+)\n\s+Repo: (.+)\n\s+Digest: (.+)/g) || [];
            
            let issueBody = `## Missing Docker Images Detected\n\n`;
            issueBody += `The scheduled validation workflow detected that ${missingImages.length} Docker image(s) are no longer available in the GitHub Container Registry.\n\n`;
            issueBody += `### Missing Images:\n\n`;
            
            missingImages.forEach(match => {
              issueBody += `\`\`\`\n${match}\n\`\`\`\n\n`;
            });
            
            issueBody += `### Recommended Actions:\n\n`;
            issueBody += `1. **Automatic Fix**: Run the [Validate Image Manifests workflow](https://github.com/${{ github.repository }}/actions/workflows/validate-manifests.yml) with "fix_missing" enabled\n`;
            issueBody += `2. **Manual Fix**: Remove the entries from manifest.json and run the build workflow\n`;
            issueBody += `3. **Investigate**: Check if there's a retention policy or other reason for image deletion\n\n`;
            issueBody += `---\n`;
            issueBody += `*This issue was automatically created by the image validation workflow.*`;
            
            // Create the issue
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Missing Docker Images in Registry (${new Date().toISOString().split('T')[0]})`,
              body: issueBody,
              labels: ['bug', 'docker', 'automated']
            });

      - name: Commit manifest changes
        if: github.event.inputs.fix_missing == 'true' && steps.validate.outputs.missing_count != '0'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check if manifest.json was modified
          if git diff --quiet manifest.json; then
            echo "No changes to manifest.json"
          else
            git add manifest.json
            git commit -m "Remove missing images from manifest.json
            
            Removed ${{ steps.validate.outputs.missing_count }} image(s) that are no longer available in the registry.
            
            This commit was automatically generated by the validate-manifests workflow."
            
            git push
          fi

      - name: Summary
        if: always()
        run: |
          echo "## Validation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.validate.outputs.exit_code }}" = "0" ]; then
            echo "✅ All images are available in the registry!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Found ${{ steps.validate.outputs.missing_count }} missing image(s)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Details:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            grep -A 4 "Missing images detected!" validation_output.txt >> $GITHUB_STEP_SUMMARY || true
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi